### PR TITLE
Add target to platformio for Archim V1

### PR DESCRIPTION
**Pull request by aznoohwee**
Add platformio target to enable build via command line.

```
pio run -e DUE_ARCHIM
```

### CODE REVIEW

**Comment by Allted** [comment]
It would be better for you to get this merged into the main Marlin2.0 bugfix branch, this isn't V1 engineering specific it would benefit everyone.

**Comment by aznoohwee** [comment]
Okay -- Theres actually no problem with the Marlin2.0 branch.

The issue was with the following commit which removed the conditional define needed for USB.

https://github.com/Allted/Marlin/commit/c4c3fc45d198476bf22ef69800a8a3f8e18707e3

**Comment by Allted** [comment]
Hmmmm, that is interesting. I will have to bring pass this info along.

**Comment by V1EngineeringInc** [comment]
I am working on the Archim1 again and needed some of your fix. I have no idea what any of this is really doing. I added,

[env:ARCHIM1]
platform      = atmelsam
board         = due
build_flags   =
  -DARDUINO_SAM_ARCHIM
  -D MOTHERBOARD="BOARD_ARCHIM1"
src_filter    = ${common.default_src_filter} +<src/HAL/HAL_DUE>

and it works, perfectly, I think. Which really is just the two build flags. 

Any idea if I am missing anything, should this be sent up the chain to Marlin as a PR?

**Comment by V1EngineeringInc** [comment]
error
Take that back I get 2 errors

**Pull request closed without merging**
